setTimeout(()=>{
    document.querySelector("P").innerHTML="10"
    setTimeout(()=>{
        document.querySelector("P").innerHTML="9"
        setTimeout(()=>{
            document.querySelector("P").innerHTML="8"
            setTimeout(()=>{
                document.querySelector("P").innerHTML="7"
                setTimeout(()=>{
                    document.querySelector("P").innerHTML="6"
                    setTimeout(()=>{
                        document.querySelector("P").innerHTML="5"
                        setTimeout(()=>{
                            document.querySelector("P").innerHTML="4"
                            setTimeout(()=>{
                                document.querySelector("P").innerHTML="3"
                                setTimeout(()=>{
                                    document.querySelector("P").innerHTML="2"
                                    setTimeout(()=>{
                                        document.querySelector("P").innerHTML="1"
                                        setTimeout(()=>{
                                            document.querySelector("P").innerHTML="Happy Independance Day"
                                        },1000)
                                    },1000)
                                },1000)
                            },1000)
                        },1000)
                    },1000)
                },1000)
            },1000)
        },1000)
    },1000)
},2000)